# VL, Variables Notes
print("Welcome to questions of the day")
print("Todays quiz is...ALL ABOUT YOU")
name= input("Tell me your name: ")

print("Hello", name)
number=input("Pick a number between 1 and 10")
print("Great choice! The number", number, "is chosen very frequently")
print("Next question:")
number_2=input("Now pick a number between 100 and 1000")
print("Wow was a fast answer! You must have been planning on saying the number", number_2, )
print("Next question:")
food=input("What did you have for breakfeast this morning")
print("Yummy!!! I wish I had",food, "this morning!")
print("Next question:")
color=input("What is your favorite color? (If you don't have one then say the color that came to your mind first)")
print("Thats a pretty color. I also like the color", color,)
print("Next question:")
school=input("What is the name of your elementary school?")
print("Wow was it good there?")
print("Next question:")
year=input("What year is it currently")
print("Dang time flies by when your having fun!")
print("Next question:")
eye=input("What is your eye color")
print("Thats very pretty!")
print("Next question:")
age=input("What is your age?")
print("Dang grandma! hahaha just kidding you don't look",age, "are your lying?")
print("Last question:")
subject=input("What was your favorite subject at school?")
print("Thats fun!!!")
print("Good bye!")

